2022-09-27 21:04:06,642:INFO:PyCaret Supervised Module
2022-09-27 21:04:06,642:INFO:ML Usecase: classification
2022-09-27 21:04:06,642:INFO:version 2.2.2
2022-09-27 21:04:06,642:INFO:Initializing setup()
2022-09-27 21:04:06,643:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:04:06,647:INFO:Checking environment
2022-09-27 21:04:06,647:INFO:python_version: 3.9.12
2022-09-27 21:04:06,648:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:04:06,648:INFO:machine: AMD64
2022-09-27 21:04:06,648:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:04:06,648:INFO:Memory: svmem(total=16959000576, available=7810822144, percent=53.9, used=9148178432, free=7810822144)
2022-09-27 21:04:06,648:INFO:Physical Core: 4
2022-09-27 21:04:06,648:INFO:Logical Core: 8
2022-09-27 21:04:06,648:INFO:Checking libraries
2022-09-27 21:04:06,648:INFO:pd==1.4.2
2022-09-27 21:04:06,648:INFO:numpy==1.21.5
2022-09-27 21:04:06,648:INFO:sklearn==1.1.2
2022-09-27 21:04:06,792:INFO:xgboost==1.6.1
2022-09-27 21:04:06,793:INFO:lightgbm==3.3.2
2022-09-27 21:04:07,262:INFO:catboost==1.0.6
2022-09-27 21:04:08,212:INFO:mlflow==1.28.0
2022-09-27 21:04:08,212:INFO:Checking Exceptions
2022-09-27 21:04:08,212:INFO:Declaring global variables
2022-09-27 21:04:08,212:INFO:USI: 9e18
2022-09-27 21:04:08,212:INFO:pycaret_globals: {'_all_models_internal', 'master_model_container', 'fix_imbalance_param', '_all_models', 'transform_target_param', '_available_plots', 'logging_param', 'create_model_container', '_internal_pipeline', 'pycaret_globals', 'display_container', 'y_test', 'data_before_preprocess', 'iterative_imputation_iters_param', 'prep_pipe', 'log_plots_param', 'y_train', '_all_metrics', 'stratify_param', 'exp_name_log', 'experiment__', 'html_param', 'fold_groups_param', '_gpu_n_jobs_param', 'X_train', 'target_param', 'X', 'imputation_regressor', 'seed', 'transform_target_method_param', 'n_jobs_param', 'gpu_param', 'fold_shuffle_param', 'USI', '_ml_usecase', 'fold_generator', 'fix_imbalance_method_param', 'X_test', 'fold_param', 'imputation_classifier', 'y'}
2022-09-27 21:04:08,212:INFO:Preparing display monitor
2022-09-27 21:04:08,213:INFO:Preparing display monitor
2022-09-27 21:04:08,222:INFO:Importing libraries
2022-09-27 21:04:08,222:INFO:Copying data for preprocessing
2022-09-27 21:04:08,228:INFO:Declaring preprocessing parameters
2022-09-27 21:04:08,229:INFO:Creating preprocessing pipeline
2022-09-27 21:04:08,230:INFO:Preprocessing pipeline created successfully
2022-09-27 21:04:08,230:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:04:08,231:INFO:Creating global containers
2022-09-27 21:05:56,566:INFO:PyCaret Supervised Module
2022-09-27 21:05:56,566:INFO:ML Usecase: classification
2022-09-27 21:05:56,566:INFO:version 2.2.2
2022-09-27 21:05:56,566:INFO:Initializing setup()
2022-09-27 21:05:56,566:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:05:56,567:INFO:Checking environment
2022-09-27 21:05:56,567:INFO:python_version: 3.9.12
2022-09-27 21:05:56,567:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:05:56,567:INFO:machine: AMD64
2022-09-27 21:05:56,567:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:05:56,567:INFO:Memory: svmem(total=16959000576, available=7982346240, percent=52.9, used=8976654336, free=7982346240)
2022-09-27 21:05:56,567:INFO:Physical Core: 4
2022-09-27 21:05:56,567:INFO:Logical Core: 8
2022-09-27 21:05:56,567:INFO:Checking libraries
2022-09-27 21:05:56,567:INFO:pd==1.4.2
2022-09-27 21:05:56,567:INFO:numpy==1.21.5
2022-09-27 21:05:56,567:INFO:sklearn==1.1.2
2022-09-27 21:05:56,595:INFO:xgboost==1.6.1
2022-09-27 21:05:56,595:INFO:lightgbm==3.3.2
2022-09-27 21:05:56,614:INFO:catboost==1.0.6
2022-09-27 21:05:57,166:INFO:mlflow==1.28.0
2022-09-27 21:05:57,166:INFO:Checking Exceptions
2022-09-27 21:05:57,166:INFO:Declaring global variables
2022-09-27 21:05:57,166:INFO:USI: 142c
2022-09-27 21:05:57,166:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:05:57,166:INFO:Preparing display monitor
2022-09-27 21:05:57,166:INFO:Preparing display monitor
2022-09-27 21:05:57,176:INFO:Importing libraries
2022-09-27 21:05:57,176:INFO:Copying data for preprocessing
2022-09-27 21:05:57,182:INFO:Declaring preprocessing parameters
2022-09-27 21:05:57,183:INFO:Creating preprocessing pipeline
2022-09-27 21:05:57,186:INFO:Preprocessing pipeline created successfully
2022-09-27 21:05:57,186:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:05:57,186:INFO:Creating global containers
2022-09-27 21:06:01,693:INFO:PyCaret Supervised Module
2022-09-27 21:06:01,693:INFO:ML Usecase: classification
2022-09-27 21:06:01,693:INFO:version 2.2.2
2022-09-27 21:06:01,693:INFO:Initializing setup()
2022-09-27 21:06:01,693:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:06:01,693:INFO:Checking environment
2022-09-27 21:06:01,693:INFO:python_version: 3.9.12
2022-09-27 21:06:01,693:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:06:01,693:INFO:machine: AMD64
2022-09-27 21:06:01,693:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:06:01,693:INFO:Memory: svmem(total=16959000576, available=7957614592, percent=53.1, used=9001385984, free=7957614592)
2022-09-27 21:06:01,694:INFO:Physical Core: 4
2022-09-27 21:06:01,694:INFO:Logical Core: 8
2022-09-27 21:06:01,694:INFO:Checking libraries
2022-09-27 21:06:01,694:INFO:pd==1.4.2
2022-09-27 21:06:01,694:INFO:numpy==1.21.5
2022-09-27 21:06:01,694:INFO:sklearn==1.1.2
2022-09-27 21:06:01,694:INFO:xgboost==1.6.1
2022-09-27 21:06:01,694:INFO:lightgbm==3.3.2
2022-09-27 21:06:01,694:INFO:catboost==1.0.6
2022-09-27 21:06:01,694:INFO:mlflow==1.28.0
2022-09-27 21:06:01,694:INFO:Checking Exceptions
2022-09-27 21:06:01,694:INFO:Declaring global variables
2022-09-27 21:06:01,694:INFO:USI: 5932
2022-09-27 21:06:01,694:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:06:01,694:INFO:Preparing display monitor
2022-09-27 21:06:01,694:INFO:Preparing display monitor
2022-09-27 21:06:01,704:INFO:Importing libraries
2022-09-27 21:06:01,704:INFO:Copying data for preprocessing
2022-09-27 21:06:01,711:INFO:Declaring preprocessing parameters
2022-09-27 21:06:01,712:INFO:Creating preprocessing pipeline
2022-09-27 21:06:01,717:INFO:Preprocessing pipeline created successfully
2022-09-27 21:06:01,717:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:06:01,717:INFO:Creating global containers
2022-09-27 21:09:27,383:INFO:PyCaret Supervised Module
2022-09-27 21:09:27,383:INFO:ML Usecase: classification
2022-09-27 21:09:27,384:INFO:version 2.2.2
2022-09-27 21:09:27,384:INFO:Initializing setup()
2022-09-27 21:09:27,384:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:09:27,384:INFO:Checking environment
2022-09-27 21:09:27,384:INFO:python_version: 3.9.12
2022-09-27 21:09:27,384:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:09:27,384:INFO:machine: AMD64
2022-09-27 21:09:27,384:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:09:27,384:INFO:Memory: svmem(total=16959000576, available=7748661248, percent=54.3, used=9210339328, free=7748661248)
2022-09-27 21:09:27,384:INFO:Physical Core: 4
2022-09-27 21:09:27,384:INFO:Logical Core: 8
2022-09-27 21:09:27,384:INFO:Checking libraries
2022-09-27 21:09:27,384:INFO:pd==1.4.2
2022-09-27 21:09:27,385:INFO:numpy==1.21.5
2022-09-27 21:09:27,385:INFO:sklearn==1.1.2
2022-09-27 21:09:27,385:INFO:xgboost==1.6.1
2022-09-27 21:09:27,385:INFO:lightgbm==3.3.2
2022-09-27 21:09:27,385:INFO:catboost==1.0.6
2022-09-27 21:09:27,385:INFO:mlflow==1.28.0
2022-09-27 21:09:27,385:INFO:Checking Exceptions
2022-09-27 21:09:27,385:INFO:Declaring global variables
2022-09-27 21:09:27,385:INFO:USI: efac
2022-09-27 21:09:27,385:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:09:27,385:INFO:Preparing display monitor
2022-09-27 21:09:27,385:INFO:Preparing display monitor
2022-09-27 21:09:27,394:INFO:Importing libraries
2022-09-27 21:09:27,395:INFO:Copying data for preprocessing
2022-09-27 21:09:27,401:INFO:Declaring preprocessing parameters
2022-09-27 21:09:27,402:INFO:Creating preprocessing pipeline
2022-09-27 21:09:27,404:INFO:Preprocessing pipeline created successfully
2022-09-27 21:09:27,404:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:09:27,404:INFO:Creating global containers
2022-09-27 21:12:54,296:INFO:PyCaret Supervised Module
2022-09-27 21:12:54,297:INFO:ML Usecase: regression
2022-09-27 21:12:54,297:INFO:version 2.2.2
2022-09-27 21:12:54,297:INFO:Initializing setup()
2022-09-27 21:12:54,297:INFO:setup(target=sentiment, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:12:54,297:INFO:Checking environment
2022-09-27 21:12:54,297:INFO:python_version: 3.9.12
2022-09-27 21:12:54,297:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:12:54,297:INFO:machine: AMD64
2022-09-27 21:12:54,297:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:12:54,297:INFO:Memory: svmem(total=16959000576, available=7745179648, percent=54.3, used=9213820928, free=7745179648)
2022-09-27 21:12:54,298:INFO:Physical Core: 4
2022-09-27 21:12:54,298:INFO:Logical Core: 8
2022-09-27 21:12:54,298:INFO:Checking libraries
2022-09-27 21:12:54,298:INFO:pd==1.4.2
2022-09-27 21:12:54,298:INFO:numpy==1.21.5
2022-09-27 21:12:54,298:INFO:sklearn==1.1.2
2022-09-27 21:12:54,298:INFO:xgboost==1.6.1
2022-09-27 21:12:54,298:INFO:lightgbm==3.3.2
2022-09-27 21:12:54,298:INFO:catboost==1.0.6
2022-09-27 21:12:54,298:INFO:mlflow==1.28.0
2022-09-27 21:12:54,298:INFO:Checking Exceptions
2022-09-27 21:12:54,298:INFO:Declaring global variables
2022-09-27 21:12:54,298:INFO:USI: 0cfe
2022-09-27 21:12:54,299:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:12:54,299:INFO:Preparing display monitor
2022-09-27 21:12:54,299:INFO:Preparing display monitor
2022-09-27 21:12:54,310:INFO:Importing libraries
2022-09-27 21:12:54,310:INFO:Copying data for preprocessing
2022-09-27 21:12:54,316:INFO:Declaring preprocessing parameters
2022-09-27 21:12:54,317:INFO:Creating preprocessing pipeline
2022-09-27 21:12:54,319:INFO:Preprocessing pipeline created successfully
2022-09-27 21:12:54,319:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:12:54,319:INFO:Creating global containers
2022-09-27 21:13:12,092:INFO:PyCaret Supervised Module
2022-09-27 21:13:12,092:INFO:ML Usecase: regression
2022-09-27 21:13:12,092:INFO:version 2.2.2
2022-09-27 21:13:12,092:INFO:Initializing setup()
2022-09-27 21:13:12,092:INFO:setup(target=sentiment, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:13:12,092:INFO:Checking environment
2022-09-27 21:13:12,093:INFO:python_version: 3.9.12
2022-09-27 21:13:12,093:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:13:12,093:INFO:machine: AMD64
2022-09-27 21:13:12,093:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:13:12,093:INFO:Memory: svmem(total=16959000576, available=7646162944, percent=54.9, used=9312837632, free=7646162944)
2022-09-27 21:13:12,093:INFO:Physical Core: 4
2022-09-27 21:13:12,093:INFO:Logical Core: 8
2022-09-27 21:13:12,093:INFO:Checking libraries
2022-09-27 21:13:12,093:INFO:pd==1.4.2
2022-09-27 21:13:12,093:INFO:numpy==1.21.5
2022-09-27 21:13:12,093:INFO:sklearn==1.1.2
2022-09-27 21:13:12,093:INFO:xgboost==1.6.1
2022-09-27 21:13:12,093:INFO:lightgbm==3.3.2
2022-09-27 21:13:12,093:INFO:catboost==1.0.6
2022-09-27 21:13:12,093:INFO:mlflow==1.28.0
2022-09-27 21:13:12,093:INFO:Checking Exceptions
2022-09-27 21:13:12,093:INFO:Declaring global variables
2022-09-27 21:13:12,093:INFO:USI: b959
2022-09-27 21:13:12,094:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:13:12,094:INFO:Preparing display monitor
2022-09-27 21:13:12,094:INFO:Preparing display monitor
2022-09-27 21:13:12,104:INFO:Importing libraries
2022-09-27 21:13:12,104:INFO:Copying data for preprocessing
2022-09-27 21:13:12,111:INFO:Declaring preprocessing parameters
2022-09-27 21:13:12,112:INFO:Creating preprocessing pipeline
2022-09-27 21:13:12,115:INFO:Preprocessing pipeline created successfully
2022-09-27 21:13:12,115:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:13:12,116:INFO:Creating global containers
2022-09-27 21:15:19,391:INFO:PyCaret Supervised Module
2022-09-27 21:15:19,392:INFO:ML Usecase: regression
2022-09-27 21:15:19,392:INFO:version 2.2.2
2022-09-27 21:15:19,392:INFO:Initializing setup()
2022-09-27 21:15:19,392:INFO:setup(target=sentiment, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:15:19,392:INFO:Checking environment
2022-09-27 21:15:19,392:INFO:python_version: 3.9.12
2022-09-27 21:15:19,392:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:15:19,392:INFO:machine: AMD64
2022-09-27 21:15:19,392:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:15:19,392:INFO:Memory: svmem(total=16959000576, available=7464636416, percent=56.0, used=9494364160, free=7464636416)
2022-09-27 21:15:19,392:INFO:Physical Core: 4
2022-09-27 21:15:19,392:INFO:Logical Core: 8
2022-09-27 21:15:19,392:INFO:Checking libraries
2022-09-27 21:15:19,392:INFO:pd==1.4.2
2022-09-27 21:15:19,392:INFO:numpy==1.21.5
2022-09-27 21:15:19,392:INFO:sklearn==1.1.2
2022-09-27 21:15:19,392:INFO:xgboost==1.6.1
2022-09-27 21:15:19,392:INFO:lightgbm==3.3.2
2022-09-27 21:15:19,392:INFO:catboost==1.0.6
2022-09-27 21:15:19,392:INFO:mlflow==1.28.0
2022-09-27 21:15:19,393:INFO:Checking Exceptions
2022-09-27 21:15:19,393:INFO:Declaring global variables
2022-09-27 21:15:19,393:INFO:USI: 45ed
2022-09-27 21:15:19,393:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:15:19,393:INFO:Preparing display monitor
2022-09-27 21:15:19,393:INFO:Preparing display monitor
2022-09-27 21:15:19,402:INFO:Importing libraries
2022-09-27 21:15:19,402:INFO:Copying data for preprocessing
2022-09-27 21:15:19,408:INFO:Declaring preprocessing parameters
2022-09-27 21:15:19,409:INFO:Creating preprocessing pipeline
2022-09-27 21:15:19,411:INFO:Preprocessing pipeline created successfully
2022-09-27 21:15:19,411:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:15:19,411:INFO:Creating global containers
2022-09-27 21:15:19,413:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:15:27,190:INFO:Creating grid variables
2022-09-27 21:15:27,203:INFO:create_model_container: 0
2022-09-27 21:15:27,203:INFO:master_model_container: 0
2022-09-27 21:15:27,203:INFO:display_container: 0
2022-09-27 21:16:58,393:INFO:PyCaret Supervised Module
2022-09-27 21:16:58,394:INFO:ML Usecase: regression
2022-09-27 21:16:58,394:INFO:version 2.2.2
2022-09-27 21:16:58,394:INFO:Initializing setup()
2022-09-27 21:16:58,394:INFO:setup(target=sentiment, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=iterative, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:16:58,394:INFO:Checking environment
2022-09-27 21:16:58,394:INFO:python_version: 3.9.12
2022-09-27 21:16:58,394:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:16:58,394:INFO:machine: AMD64
2022-09-27 21:16:58,394:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:16:58,394:INFO:Memory: svmem(total=16959000576, available=7696646144, percent=54.6, used=9262354432, free=7696646144)
2022-09-27 21:16:58,394:INFO:Physical Core: 4
2022-09-27 21:16:58,394:INFO:Logical Core: 8
2022-09-27 21:16:58,395:INFO:Checking libraries
2022-09-27 21:16:58,395:INFO:pd==1.4.2
2022-09-27 21:16:58,395:INFO:numpy==1.21.5
2022-09-27 21:16:58,395:INFO:sklearn==1.1.2
2022-09-27 21:16:58,395:INFO:xgboost==1.6.1
2022-09-27 21:16:58,395:INFO:lightgbm==3.3.2
2022-09-27 21:16:58,395:INFO:catboost==1.0.6
2022-09-27 21:16:58,395:INFO:mlflow==1.28.0
2022-09-27 21:16:58,395:INFO:Checking Exceptions
2022-09-27 21:16:58,395:INFO:Declaring global variables
2022-09-27 21:16:58,395:INFO:USI: ad37
2022-09-27 21:16:58,395:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:16:58,396:INFO:Preparing display monitor
2022-09-27 21:16:58,396:INFO:Preparing display monitor
2022-09-27 21:16:58,406:INFO:Importing libraries
2022-09-27 21:16:58,406:INFO:Copying data for preprocessing
2022-09-27 21:16:58,412:INFO:Declaring preprocessing parameters
2022-09-27 21:16:58,413:INFO:Setting up iterative imputation
2022-09-27 21:16:58,647:INFO:Creating preprocessing pipeline
2022-09-27 21:16:58,649:INFO:Preprocessing pipeline created successfully
2022-09-27 21:16:58,649:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:16:58,649:INFO:Creating global containers
2022-09-27 21:16:58,649:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:17:02,864:INFO:Creating grid variables
2022-09-27 21:17:02,872:INFO:create_model_container: 0
2022-09-27 21:17:02,872:INFO:master_model_container: 0
2022-09-27 21:17:02,873:INFO:display_container: 0
2022-09-27 21:20:13,678:INFO:PyCaret Supervised Module
2022-09-27 21:20:13,679:INFO:ML Usecase: classification
2022-09-27 21:20:13,679:INFO:version 2.2.2
2022-09-27 21:20:13,679:INFO:Initializing setup()
2022-09-27 21:20:13,679:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=iterative, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:20:13,679:INFO:Checking environment
2022-09-27 21:20:13,679:INFO:python_version: 3.9.12
2022-09-27 21:20:13,679:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:20:13,679:INFO:machine: AMD64
2022-09-27 21:20:13,679:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:20:13,679:INFO:Memory: svmem(total=16959000576, available=7391084544, percent=56.4, used=9567916032, free=7391084544)
2022-09-27 21:20:13,680:INFO:Physical Core: 4
2022-09-27 21:20:13,680:INFO:Logical Core: 8
2022-09-27 21:20:13,680:INFO:Checking libraries
2022-09-27 21:20:13,680:INFO:pd==1.4.2
2022-09-27 21:20:13,680:INFO:numpy==1.21.5
2022-09-27 21:20:13,680:INFO:sklearn==1.1.2
2022-09-27 21:20:13,680:INFO:xgboost==1.6.1
2022-09-27 21:20:13,680:INFO:lightgbm==3.3.2
2022-09-27 21:20:13,680:INFO:catboost==1.0.6
2022-09-27 21:20:13,680:INFO:mlflow==1.28.0
2022-09-27 21:20:13,680:INFO:Checking Exceptions
2022-09-27 21:20:13,680:INFO:Declaring global variables
2022-09-27 21:20:13,680:INFO:USI: a430
2022-09-27 21:20:13,680:INFO:pycaret_globals: {'create_model_container', 'X_train', 'gpu_param', 'html_param', 'pycaret_globals', 'log_plots_param', 'transform_target_method_param', 'fold_shuffle_param', 'y_train', 'exp_name_log', 'iterative_imputation_iters_param', '_internal_pipeline', '_all_models', '_gpu_n_jobs_param', 'seed', 'prep_pipe', '_available_plots', 'X_test', 'imputation_regressor', 'fold_groups_param', 'data_before_preprocess', '_all_metrics', '_ml_usecase', 'display_container', 'target_param', 'master_model_container', '_all_models_internal', 'fix_imbalance_param', 'USI', 'y', 'stratify_param', 'y_test', 'fold_param', 'X', 'fold_generator', 'experiment__', 'logging_param', 'n_jobs_param', 'transform_target_param', 'imputation_classifier', 'fix_imbalance_method_param'}
2022-09-27 21:20:13,680:INFO:Preparing display monitor
2022-09-27 21:20:13,680:INFO:Preparing display monitor
2022-09-27 21:20:13,692:INFO:Importing libraries
2022-09-27 21:20:13,692:INFO:Copying data for preprocessing
2022-09-27 21:20:13,698:INFO:Declaring preprocessing parameters
2022-09-27 21:20:13,699:INFO:Setting up iterative imputation
2022-09-27 21:20:13,893:INFO:Creating preprocessing pipeline
2022-09-27 21:20:13,895:INFO:Preprocessing pipeline created successfully
2022-09-27 21:20:13,895:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:20:13,895:INFO:Creating global containers
2022-09-27 21:20:13,895:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:20:17,731:INFO:Creating grid variables
2022-09-27 21:20:17,739:INFO:create_model_container: 0
2022-09-27 21:20:17,740:INFO:master_model_container: 0
2022-09-27 21:20:17,740:INFO:display_container: 0
2022-09-27 21:20:51,936:INFO:PyCaret Supervised Module
2022-09-27 21:20:51,936:INFO:ML Usecase: classification
2022-09-27 21:20:51,936:INFO:version 2.2.2
2022-09-27 21:20:51,936:INFO:Initializing setup()
2022-09-27 21:20:51,937:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=iterative, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:20:51,937:INFO:Checking environment
2022-09-27 21:20:51,937:INFO:python_version: 3.9.12
2022-09-27 21:20:51,937:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:20:51,937:INFO:machine: AMD64
2022-09-27 21:20:51,937:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:20:51,937:INFO:Memory: svmem(total=16959000576, available=7428890624, percent=56.2, used=9530109952, free=7428890624)
2022-09-27 21:20:51,937:INFO:Physical Core: 4
2022-09-27 21:20:51,937:INFO:Logical Core: 8
2022-09-27 21:20:51,938:INFO:Checking libraries
2022-09-27 21:20:51,938:INFO:pd==1.4.2
2022-09-27 21:20:51,938:INFO:numpy==1.21.5
2022-09-27 21:20:51,938:INFO:sklearn==1.1.2
2022-09-27 21:20:51,965:INFO:xgboost==1.6.1
2022-09-27 21:20:51,965:INFO:lightgbm==3.3.2
2022-09-27 21:20:51,982:INFO:catboost==1.0.6
2022-09-27 21:20:52,678:INFO:mlflow==1.28.0
2022-09-27 21:20:52,678:INFO:Checking Exceptions
2022-09-27 21:20:52,678:INFO:Declaring global variables
2022-09-27 21:20:52,678:INFO:USI: 342f
2022-09-27 21:20:52,678:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:20:52,678:INFO:Preparing display monitor
2022-09-27 21:20:52,678:INFO:Preparing display monitor
2022-09-27 21:20:52,688:INFO:Importing libraries
2022-09-27 21:20:52,688:INFO:Copying data for preprocessing
2022-09-27 21:20:52,695:INFO:Declaring preprocessing parameters
2022-09-27 21:20:52,696:INFO:Setting up iterative imputation
2022-09-27 21:20:52,964:INFO:Creating preprocessing pipeline
2022-09-27 21:20:52,966:INFO:Preprocessing pipeline created successfully
2022-09-27 21:20:52,966:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:20:52,966:INFO:Creating global containers
2022-09-27 21:20:52,967:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:20:56,873:INFO:Creating grid variables
2022-09-27 21:20:56,883:INFO:create_model_container: 0
2022-09-27 21:20:56,883:INFO:master_model_container: 0
2022-09-27 21:20:56,883:INFO:display_container: 0
2022-09-27 21:22:27,855:INFO:PyCaret Supervised Module
2022-09-27 21:22:27,855:INFO:ML Usecase: classification
2022-09-27 21:22:27,855:INFO:version 2.2.2
2022-09-27 21:22:27,855:INFO:Initializing setup()
2022-09-27 21:22:27,855:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=iterative, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:22:27,856:INFO:Checking environment
2022-09-27 21:22:27,856:INFO:python_version: 3.9.12
2022-09-27 21:22:27,856:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:22:27,856:INFO:machine: AMD64
2022-09-27 21:22:27,856:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:22:27,856:INFO:Memory: svmem(total=16959000576, available=7401725952, percent=56.4, used=9557274624, free=7401725952)
2022-09-27 21:22:27,856:INFO:Physical Core: 4
2022-09-27 21:22:27,856:INFO:Logical Core: 8
2022-09-27 21:22:27,856:INFO:Checking libraries
2022-09-27 21:22:27,856:INFO:pd==1.4.2
2022-09-27 21:22:27,856:INFO:numpy==1.21.5
2022-09-27 21:22:27,856:INFO:sklearn==1.1.2
2022-09-27 21:22:27,856:INFO:xgboost==1.6.1
2022-09-27 21:22:27,856:INFO:lightgbm==3.3.2
2022-09-27 21:22:27,856:INFO:catboost==1.0.6
2022-09-27 21:22:27,856:INFO:mlflow==1.28.0
2022-09-27 21:22:27,857:INFO:Checking Exceptions
2022-09-27 21:22:27,857:INFO:Declaring global variables
2022-09-27 21:22:27,857:INFO:USI: b690
2022-09-27 21:22:27,857:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:22:27,857:INFO:Preparing display monitor
2022-09-27 21:22:27,857:INFO:Preparing display monitor
2022-09-27 21:22:27,867:INFO:Importing libraries
2022-09-27 21:22:27,867:INFO:Copying data for preprocessing
2022-09-27 21:22:27,873:INFO:Declaring preprocessing parameters
2022-09-27 21:22:27,874:INFO:Setting up iterative imputation
2022-09-27 21:22:28,074:INFO:Creating preprocessing pipeline
2022-09-27 21:22:28,076:INFO:Preprocessing pipeline created successfully
2022-09-27 21:22:28,076:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:22:28,076:INFO:Creating global containers
2022-09-27 21:22:28,076:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:22:31,583:INFO:Creating grid variables
2022-09-27 21:22:31,593:INFO:create_model_container: 0
2022-09-27 21:22:31,593:INFO:master_model_container: 0
2022-09-27 21:22:31,593:INFO:display_container: 0
2022-09-27 21:22:47,789:INFO:PyCaret Supervised Module
2022-09-27 21:22:47,789:INFO:ML Usecase: classification
2022-09-27 21:22:47,789:INFO:version 2.2.2
2022-09-27 21:22:47,789:INFO:Initializing setup()
2022-09-27 21:22:47,789:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:22:47,789:INFO:Checking environment
2022-09-27 21:22:47,789:INFO:python_version: 3.9.12
2022-09-27 21:22:47,790:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:22:47,790:INFO:machine: AMD64
2022-09-27 21:22:47,790:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:22:47,790:INFO:Memory: svmem(total=16959000576, available=7369867264, percent=56.5, used=9589133312, free=7369867264)
2022-09-27 21:22:47,790:INFO:Physical Core: 4
2022-09-27 21:22:47,790:INFO:Logical Core: 8
2022-09-27 21:22:47,790:INFO:Checking libraries
2022-09-27 21:22:47,790:INFO:pd==1.4.2
2022-09-27 21:22:47,790:INFO:numpy==1.21.5
2022-09-27 21:22:47,790:INFO:sklearn==1.1.2
2022-09-27 21:22:47,790:INFO:xgboost==1.6.1
2022-09-27 21:22:47,790:INFO:lightgbm==3.3.2
2022-09-27 21:22:47,790:INFO:catboost==1.0.6
2022-09-27 21:22:47,790:INFO:mlflow==1.28.0
2022-09-27 21:22:47,790:INFO:Checking Exceptions
2022-09-27 21:22:47,790:INFO:Declaring global variables
2022-09-27 21:22:47,790:INFO:USI: 9215
2022-09-27 21:22:47,790:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:22:47,790:INFO:Preparing display monitor
2022-09-27 21:22:47,791:INFO:Preparing display monitor
2022-09-27 21:22:47,799:INFO:Importing libraries
2022-09-27 21:22:47,800:INFO:Copying data for preprocessing
2022-09-27 21:22:47,807:INFO:Declaring preprocessing parameters
2022-09-27 21:22:47,808:INFO:Creating preprocessing pipeline
2022-09-27 21:22:47,810:INFO:Preprocessing pipeline created successfully
2022-09-27 21:22:47,810:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:22:47,810:INFO:Creating global containers
2022-09-27 21:24:14,854:INFO:PyCaret Supervised Module
2022-09-27 21:24:14,854:INFO:ML Usecase: classification
2022-09-27 21:24:14,854:INFO:version 2.2.2
2022-09-27 21:24:14,854:INFO:Initializing setup()
2022-09-27 21:24:14,854:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=iterative, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=True, multicollinearity_threshold=0.95, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:24:14,855:INFO:Checking environment
2022-09-27 21:24:14,855:INFO:python_version: 3.9.12
2022-09-27 21:24:14,855:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:24:14,855:INFO:machine: AMD64
2022-09-27 21:24:14,855:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:24:14,855:INFO:Memory: svmem(total=16959000576, available=7159508992, percent=57.8, used=9799491584, free=7159508992)
2022-09-27 21:24:14,855:INFO:Physical Core: 4
2022-09-27 21:24:14,855:INFO:Logical Core: 8
2022-09-27 21:24:14,855:INFO:Checking libraries
2022-09-27 21:24:14,855:INFO:pd==1.4.2
2022-09-27 21:24:14,855:INFO:numpy==1.21.5
2022-09-27 21:24:14,855:INFO:sklearn==1.1.2
2022-09-27 21:24:14,855:INFO:xgboost==1.6.1
2022-09-27 21:24:14,855:INFO:lightgbm==3.3.2
2022-09-27 21:24:14,855:INFO:catboost==1.0.6
2022-09-27 21:24:14,855:INFO:mlflow==1.28.0
2022-09-27 21:24:14,855:INFO:Checking Exceptions
2022-09-27 21:24:14,855:INFO:Declaring global variables
2022-09-27 21:24:14,856:INFO:USI: 6ccf
2022-09-27 21:24:14,856:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:24:14,856:INFO:Preparing display monitor
2022-09-27 21:24:14,856:INFO:Preparing display monitor
2022-09-27 21:24:14,865:INFO:Importing libraries
2022-09-27 21:24:14,865:INFO:Copying data for preprocessing
2022-09-27 21:24:14,871:INFO:Declaring preprocessing parameters
2022-09-27 21:24:14,872:INFO:Setting up iterative imputation
2022-09-27 21:24:15,077:INFO:Creating preprocessing pipeline
2022-09-27 21:24:15,079:INFO:Preprocessing pipeline created successfully
2022-09-27 21:24:15,079:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:24:15,079:INFO:Creating global containers
2022-09-27 21:24:15,079:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=2,
                       sampling_strategy='auto'))],
         verbose=False)
2022-09-27 21:24:18,192:INFO:Creating grid variables
2022-09-27 21:24:18,200:INFO:create_model_container: 0
2022-09-27 21:24:18,200:INFO:master_model_container: 0
2022-09-27 21:24:18,200:INFO:display_container: 0
2022-09-27 21:24:35,596:INFO:PyCaret Supervised Module
2022-09-27 21:24:35,597:INFO:ML Usecase: classification
2022-09-27 21:24:35,597:INFO:version 2.2.2
2022-09-27 21:24:35,597:INFO:Initializing setup()
2022-09-27 21:24:35,597:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=True, multicollinearity_threshold=0.95, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:24:35,597:INFO:Checking environment
2022-09-27 21:24:35,597:INFO:python_version: 3.9.12
2022-09-27 21:24:35,597:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:24:35,597:INFO:machine: AMD64
2022-09-27 21:24:35,597:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:24:35,597:INFO:Memory: svmem(total=16959000576, available=7164903424, percent=57.8, used=9794097152, free=7164903424)
2022-09-27 21:24:35,598:INFO:Physical Core: 4
2022-09-27 21:24:35,598:INFO:Logical Core: 8
2022-09-27 21:24:35,598:INFO:Checking libraries
2022-09-27 21:24:35,598:INFO:pd==1.4.2
2022-09-27 21:24:35,598:INFO:numpy==1.21.5
2022-09-27 21:24:35,598:INFO:sklearn==1.1.2
2022-09-27 21:24:35,598:INFO:xgboost==1.6.1
2022-09-27 21:24:35,598:INFO:lightgbm==3.3.2
2022-09-27 21:24:35,598:INFO:catboost==1.0.6
2022-09-27 21:24:35,598:INFO:mlflow==1.28.0
2022-09-27 21:24:35,598:INFO:Checking Exceptions
2022-09-27 21:24:35,598:INFO:Declaring global variables
2022-09-27 21:24:35,598:INFO:USI: d5d2
2022-09-27 21:24:35,599:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:24:35,599:INFO:Preparing display monitor
2022-09-27 21:24:35,599:INFO:Preparing display monitor
2022-09-27 21:24:35,612:INFO:Importing libraries
2022-09-27 21:24:35,612:INFO:Copying data for preprocessing
2022-09-27 21:24:35,619:INFO:Declaring preprocessing parameters
2022-09-27 21:24:35,619:INFO:Creating preprocessing pipeline
2022-09-27 21:24:35,621:INFO:Preprocessing pipeline created successfully
2022-09-27 21:24:35,622:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:24:35,622:INFO:Creating global containers
2022-09-27 21:24:35,622:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=2,
                       sampling_strategy='auto'))],
         verbose=False)
2022-09-27 21:24:40,660:INFO:Creating grid variables
2022-09-27 21:24:40,668:INFO:create_model_container: 0
2022-09-27 21:24:40,668:INFO:master_model_container: 0
2022-09-27 21:24:40,669:INFO:display_container: 0
2022-09-27 21:24:59,093:INFO:PyCaret Supervised Module
2022-09-27 21:24:59,094:INFO:ML Usecase: classification
2022-09-27 21:24:59,094:INFO:version 2.2.2
2022-09-27 21:24:59,094:INFO:Initializing setup()
2022-09-27 21:24:59,094:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:24:59,094:INFO:Checking environment
2022-09-27 21:24:59,094:INFO:python_version: 3.9.12
2022-09-27 21:24:59,094:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:24:59,094:INFO:machine: AMD64
2022-09-27 21:24:59,094:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:24:59,094:INFO:Memory: svmem(total=16959000576, available=7127572480, percent=58.0, used=9831428096, free=7127572480)
2022-09-27 21:24:59,094:INFO:Physical Core: 4
2022-09-27 21:24:59,094:INFO:Logical Core: 8
2022-09-27 21:24:59,095:INFO:Checking libraries
2022-09-27 21:24:59,095:INFO:pd==1.4.2
2022-09-27 21:24:59,095:INFO:numpy==1.21.5
2022-09-27 21:24:59,095:INFO:sklearn==1.1.2
2022-09-27 21:24:59,095:INFO:xgboost==1.6.1
2022-09-27 21:24:59,095:INFO:lightgbm==3.3.2
2022-09-27 21:24:59,095:INFO:catboost==1.0.6
2022-09-27 21:24:59,095:INFO:mlflow==1.28.0
2022-09-27 21:24:59,095:INFO:Checking Exceptions
2022-09-27 21:24:59,095:INFO:Declaring global variables
2022-09-27 21:24:59,095:INFO:USI: 1dfa
2022-09-27 21:24:59,095:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:24:59,096:INFO:Preparing display monitor
2022-09-27 21:24:59,096:INFO:Preparing display monitor
2022-09-27 21:24:59,106:INFO:Importing libraries
2022-09-27 21:24:59,106:INFO:Copying data for preprocessing
2022-09-27 21:24:59,113:INFO:Declaring preprocessing parameters
2022-09-27 21:24:59,114:INFO:Creating preprocessing pipeline
2022-09-27 21:24:59,116:INFO:Preprocessing pipeline created successfully
2022-09-27 21:24:59,116:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:24:59,116:INFO:Creating global containers
2022-09-27 21:25:24,074:INFO:Initializing compare_models()
2022-09-27 21:25:24,075:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2022-09-27 21:25:24,075:INFO:Checking exceptions
2022-09-27 21:25:24,075:INFO:Preparing display monitor
2022-09-27 21:25:24,075:INFO:Preparing display monitor
2022-09-27 21:25:24,097:INFO:Initializing Logistic Regression
2022-09-27 21:25:24,097:INFO:Total runtime is 0.0 minutes
2022-09-27 21:25:24,104:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,104:INFO:Initializing create_model()
2022-09-27 21:25:24,104:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,104:INFO:Checking exceptions
2022-09-27 21:25:24,104:INFO:Importing libraries
2022-09-27 21:25:24,104:INFO:Copying training dataset
2022-09-27 21:25:24,105:INFO:Defining folds
2022-09-27 21:25:24,105:INFO:Declaring metric variables
2022-09-27 21:25:24,111:INFO:Importing untrained model
2022-09-27 21:25:24,119:INFO:Logistic Regression Imported succesfully
2022-09-27 21:25:24,135:INFO:Starting cross validation
2022-09-27 21:25:24,136:WARNING:create_model() for lr raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,144:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,144:INFO:Initializing create_model()
2022-09-27 21:25:24,144:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,144:INFO:Checking exceptions
2022-09-27 21:25:24,144:INFO:Importing libraries
2022-09-27 21:25:24,144:INFO:Copying training dataset
2022-09-27 21:25:24,145:INFO:Defining folds
2022-09-27 21:25:24,145:INFO:Declaring metric variables
2022-09-27 21:25:24,152:INFO:Importing untrained model
2022-09-27 21:25:24,158:INFO:Logistic Regression Imported succesfully
2022-09-27 21:25:24,171:INFO:Starting cross validation
2022-09-27 21:25:24,171:ERROR:create_model() for lr raised an exception:
2022-09-27 21:25:24,172:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,172:INFO:Initializing K Neighbors Classifier
2022-09-27 21:25:24,173:INFO:Total runtime is 0.0012693007787068684 minutes
2022-09-27 21:25:24,180:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,180:INFO:Initializing create_model()
2022-09-27 21:25:24,180:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,180:INFO:Checking exceptions
2022-09-27 21:25:24,180:INFO:Importing libraries
2022-09-27 21:25:24,180:INFO:Copying training dataset
2022-09-27 21:25:24,181:INFO:Defining folds
2022-09-27 21:25:24,181:INFO:Declaring metric variables
2022-09-27 21:25:24,188:INFO:Importing untrained model
2022-09-27 21:25:24,194:INFO:K Neighbors Classifier Imported succesfully
2022-09-27 21:25:24,207:INFO:Starting cross validation
2022-09-27 21:25:24,207:WARNING:create_model() for knn raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,208:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,208:INFO:Initializing create_model()
2022-09-27 21:25:24,208:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,208:INFO:Checking exceptions
2022-09-27 21:25:24,209:INFO:Importing libraries
2022-09-27 21:25:24,209:INFO:Copying training dataset
2022-09-27 21:25:24,209:INFO:Defining folds
2022-09-27 21:25:24,209:INFO:Declaring metric variables
2022-09-27 21:25:24,219:INFO:Importing untrained model
2022-09-27 21:25:24,226:INFO:K Neighbors Classifier Imported succesfully
2022-09-27 21:25:24,246:INFO:Starting cross validation
2022-09-27 21:25:24,247:ERROR:create_model() for knn raised an exception:
2022-09-27 21:25:24,248:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,248:INFO:Initializing Naive Bayes
2022-09-27 21:25:24,248:INFO:Total runtime is 0.002516019344329834 minutes
2022-09-27 21:25:24,255:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,255:INFO:Initializing create_model()
2022-09-27 21:25:24,255:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,255:INFO:Checking exceptions
2022-09-27 21:25:24,255:INFO:Importing libraries
2022-09-27 21:25:24,255:INFO:Copying training dataset
2022-09-27 21:25:24,256:INFO:Defining folds
2022-09-27 21:25:24,256:INFO:Declaring metric variables
2022-09-27 21:25:24,262:INFO:Importing untrained model
2022-09-27 21:25:24,269:INFO:Naive Bayes Imported succesfully
2022-09-27 21:25:24,284:INFO:Starting cross validation
2022-09-27 21:25:24,285:WARNING:create_model() for nb raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,285:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,286:INFO:Initializing create_model()
2022-09-27 21:25:24,286:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,286:INFO:Checking exceptions
2022-09-27 21:25:24,286:INFO:Importing libraries
2022-09-27 21:25:24,286:INFO:Copying training dataset
2022-09-27 21:25:24,287:INFO:Defining folds
2022-09-27 21:25:24,287:INFO:Declaring metric variables
2022-09-27 21:25:24,293:INFO:Importing untrained model
2022-09-27 21:25:24,299:INFO:Naive Bayes Imported succesfully
2022-09-27 21:25:24,312:INFO:Starting cross validation
2022-09-27 21:25:24,312:ERROR:create_model() for nb raised an exception:
2022-09-27 21:25:24,313:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,313:INFO:Initializing Decision Tree Classifier
2022-09-27 21:25:24,313:INFO:Total runtime is 0.0035964171091715496 minutes
2022-09-27 21:25:24,320:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,320:INFO:Initializing create_model()
2022-09-27 21:25:24,320:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,320:INFO:Checking exceptions
2022-09-27 21:25:24,320:INFO:Importing libraries
2022-09-27 21:25:24,321:INFO:Copying training dataset
2022-09-27 21:25:24,321:INFO:Defining folds
2022-09-27 21:25:24,321:INFO:Declaring metric variables
2022-09-27 21:25:24,328:INFO:Importing untrained model
2022-09-27 21:25:24,334:INFO:Decision Tree Classifier Imported succesfully
2022-09-27 21:25:24,347:INFO:Starting cross validation
2022-09-27 21:25:24,348:WARNING:create_model() for dt raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,348:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,348:INFO:Initializing create_model()
2022-09-27 21:25:24,349:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,349:INFO:Checking exceptions
2022-09-27 21:25:24,349:INFO:Importing libraries
2022-09-27 21:25:24,349:INFO:Copying training dataset
2022-09-27 21:25:24,350:INFO:Defining folds
2022-09-27 21:25:24,350:INFO:Declaring metric variables
2022-09-27 21:25:24,356:INFO:Importing untrained model
2022-09-27 21:25:24,362:INFO:Decision Tree Classifier Imported succesfully
2022-09-27 21:25:24,376:INFO:Starting cross validation
2022-09-27 21:25:24,376:ERROR:create_model() for dt raised an exception:
2022-09-27 21:25:24,377:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,377:INFO:Initializing SVM - Linear Kernel
2022-09-27 21:25:24,377:INFO:Total runtime is 0.004660224914550782 minutes
2022-09-27 21:25:24,384:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,385:INFO:Initializing create_model()
2022-09-27 21:25:24,385:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,385:INFO:Checking exceptions
2022-09-27 21:25:24,385:INFO:Importing libraries
2022-09-27 21:25:24,385:INFO:Copying training dataset
2022-09-27 21:25:24,386:INFO:Defining folds
2022-09-27 21:25:24,386:INFO:Declaring metric variables
2022-09-27 21:25:24,392:INFO:Importing untrained model
2022-09-27 21:25:24,398:INFO:SVM - Linear Kernel Imported succesfully
2022-09-27 21:25:24,411:INFO:Starting cross validation
2022-09-27 21:25:24,411:WARNING:create_model() for svm raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,411:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,412:INFO:Initializing create_model()
2022-09-27 21:25:24,412:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,412:INFO:Checking exceptions
2022-09-27 21:25:24,413:INFO:Importing libraries
2022-09-27 21:25:24,413:INFO:Copying training dataset
2022-09-27 21:25:24,414:INFO:Defining folds
2022-09-27 21:25:24,414:INFO:Declaring metric variables
2022-09-27 21:25:24,421:INFO:Importing untrained model
2022-09-27 21:25:24,428:INFO:SVM - Linear Kernel Imported succesfully
2022-09-27 21:25:24,441:INFO:Starting cross validation
2022-09-27 21:25:24,441:ERROR:create_model() for svm raised an exception:
2022-09-27 21:25:24,442:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,442:INFO:Initializing Ridge Classifier
2022-09-27 21:25:24,442:INFO:Total runtime is 0.005740710099538167 minutes
2022-09-27 21:25:24,449:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,449:INFO:Initializing create_model()
2022-09-27 21:25:24,449:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,449:INFO:Checking exceptions
2022-09-27 21:25:24,449:INFO:Importing libraries
2022-09-27 21:25:24,449:INFO:Copying training dataset
2022-09-27 21:25:24,450:INFO:Defining folds
2022-09-27 21:25:24,451:INFO:Declaring metric variables
2022-09-27 21:25:24,457:INFO:Importing untrained model
2022-09-27 21:25:24,465:INFO:Ridge Classifier Imported succesfully
2022-09-27 21:25:24,480:INFO:Starting cross validation
2022-09-27 21:25:24,480:WARNING:create_model() for ridge raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,480:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,480:INFO:Initializing create_model()
2022-09-27 21:25:24,480:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,480:INFO:Checking exceptions
2022-09-27 21:25:24,481:INFO:Importing libraries
2022-09-27 21:25:24,481:INFO:Copying training dataset
2022-09-27 21:25:24,481:INFO:Defining folds
2022-09-27 21:25:24,481:INFO:Declaring metric variables
2022-09-27 21:25:24,488:INFO:Importing untrained model
2022-09-27 21:25:24,494:INFO:Ridge Classifier Imported succesfully
2022-09-27 21:25:24,507:INFO:Starting cross validation
2022-09-27 21:25:24,508:ERROR:create_model() for ridge raised an exception:
2022-09-27 21:25:24,508:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,509:INFO:Initializing Random Forest Classifier
2022-09-27 21:25:24,509:INFO:Total runtime is 0.0068543831507364905 minutes
2022-09-27 21:25:24,516:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,517:INFO:Initializing create_model()
2022-09-27 21:25:24,517:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,517:INFO:Checking exceptions
2022-09-27 21:25:24,517:INFO:Importing libraries
2022-09-27 21:25:24,517:INFO:Copying training dataset
2022-09-27 21:25:24,517:INFO:Defining folds
2022-09-27 21:25:24,517:INFO:Declaring metric variables
2022-09-27 21:25:24,524:INFO:Importing untrained model
2022-09-27 21:25:24,529:INFO:Random Forest Classifier Imported succesfully
2022-09-27 21:25:24,544:INFO:Starting cross validation
2022-09-27 21:25:24,545:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,545:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,545:INFO:Initializing create_model()
2022-09-27 21:25:24,545:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,546:INFO:Checking exceptions
2022-09-27 21:25:24,546:INFO:Importing libraries
2022-09-27 21:25:24,546:INFO:Copying training dataset
2022-09-27 21:25:24,547:INFO:Defining folds
2022-09-27 21:25:24,547:INFO:Declaring metric variables
2022-09-27 21:25:24,556:INFO:Importing untrained model
2022-09-27 21:25:24,562:INFO:Random Forest Classifier Imported succesfully
2022-09-27 21:25:24,585:INFO:Starting cross validation
2022-09-27 21:25:24,585:ERROR:create_model() for rf raised an exception:
2022-09-27 21:25:24,586:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,586:INFO:Initializing Quadratic Discriminant Analysis
2022-09-27 21:25:24,586:INFO:Total runtime is 0.008150895436604817 minutes
2022-09-27 21:25:24,593:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,593:INFO:Initializing create_model()
2022-09-27 21:25:24,593:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,593:INFO:Checking exceptions
2022-09-27 21:25:24,593:INFO:Importing libraries
2022-09-27 21:25:24,594:INFO:Copying training dataset
2022-09-27 21:25:24,594:INFO:Defining folds
2022-09-27 21:25:24,594:INFO:Declaring metric variables
2022-09-27 21:25:24,600:INFO:Importing untrained model
2022-09-27 21:25:24,606:INFO:Quadratic Discriminant Analysis Imported succesfully
2022-09-27 21:25:24,622:INFO:Starting cross validation
2022-09-27 21:25:24,622:WARNING:create_model() for qda raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,622:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,623:INFO:Initializing create_model()
2022-09-27 21:25:24,623:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,623:INFO:Checking exceptions
2022-09-27 21:25:24,623:INFO:Importing libraries
2022-09-27 21:25:24,623:INFO:Copying training dataset
2022-09-27 21:25:24,624:INFO:Defining folds
2022-09-27 21:25:24,624:INFO:Declaring metric variables
2022-09-27 21:25:24,629:INFO:Importing untrained model
2022-09-27 21:25:24,637:INFO:Quadratic Discriminant Analysis Imported succesfully
2022-09-27 21:25:24,650:INFO:Starting cross validation
2022-09-27 21:25:24,650:ERROR:create_model() for qda raised an exception:
2022-09-27 21:25:24,651:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,651:INFO:Initializing Ada Boost Classifier
2022-09-27 21:25:24,651:INFO:Total runtime is 0.009231368700663248 minutes
2022-09-27 21:25:24,658:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,658:INFO:Initializing create_model()
2022-09-27 21:25:24,659:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,659:INFO:Checking exceptions
2022-09-27 21:25:24,659:INFO:Importing libraries
2022-09-27 21:25:24,659:INFO:Copying training dataset
2022-09-27 21:25:24,660:INFO:Defining folds
2022-09-27 21:25:24,660:INFO:Declaring metric variables
2022-09-27 21:25:24,666:INFO:Importing untrained model
2022-09-27 21:25:24,672:INFO:Ada Boost Classifier Imported succesfully
2022-09-27 21:25:24,686:INFO:Starting cross validation
2022-09-27 21:25:24,686:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,687:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,687:INFO:Initializing create_model()
2022-09-27 21:25:24,687:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,687:INFO:Checking exceptions
2022-09-27 21:25:24,687:INFO:Importing libraries
2022-09-27 21:25:24,687:INFO:Copying training dataset
2022-09-27 21:25:24,688:INFO:Defining folds
2022-09-27 21:25:24,688:INFO:Declaring metric variables
2022-09-27 21:25:24,694:INFO:Importing untrained model
2022-09-27 21:25:24,700:INFO:Ada Boost Classifier Imported succesfully
2022-09-27 21:25:24,715:INFO:Starting cross validation
2022-09-27 21:25:24,716:ERROR:create_model() for ada raised an exception:
2022-09-27 21:25:24,717:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,717:INFO:Initializing Gradient Boosting Classifier
2022-09-27 21:25:24,717:INFO:Total runtime is 0.010328416029612222 minutes
2022-09-27 21:25:24,725:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,725:INFO:Initializing create_model()
2022-09-27 21:25:24,725:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,725:INFO:Checking exceptions
2022-09-27 21:25:24,725:INFO:Importing libraries
2022-09-27 21:25:24,725:INFO:Copying training dataset
2022-09-27 21:25:24,726:INFO:Defining folds
2022-09-27 21:25:24,726:INFO:Declaring metric variables
2022-09-27 21:25:24,732:INFO:Importing untrained model
2022-09-27 21:25:24,738:INFO:Gradient Boosting Classifier Imported succesfully
2022-09-27 21:25:24,752:INFO:Starting cross validation
2022-09-27 21:25:24,752:WARNING:create_model() for gbc raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,753:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,753:INFO:Initializing create_model()
2022-09-27 21:25:24,753:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,753:INFO:Checking exceptions
2022-09-27 21:25:24,753:INFO:Importing libraries
2022-09-27 21:25:24,754:INFO:Copying training dataset
2022-09-27 21:25:24,754:INFO:Defining folds
2022-09-27 21:25:24,754:INFO:Declaring metric variables
2022-09-27 21:25:24,760:INFO:Importing untrained model
2022-09-27 21:25:24,767:INFO:Gradient Boosting Classifier Imported succesfully
2022-09-27 21:25:24,779:INFO:Starting cross validation
2022-09-27 21:25:24,779:ERROR:create_model() for gbc raised an exception:
2022-09-27 21:25:24,780:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,781:INFO:Initializing Linear Discriminant Analysis
2022-09-27 21:25:24,781:INFO:Total runtime is 0.01140071153640747 minutes
2022-09-27 21:25:24,788:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,788:INFO:Initializing create_model()
2022-09-27 21:25:24,788:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,788:INFO:Checking exceptions
2022-09-27 21:25:24,788:INFO:Importing libraries
2022-09-27 21:25:24,789:INFO:Copying training dataset
2022-09-27 21:25:24,790:INFO:Defining folds
2022-09-27 21:25:24,790:INFO:Declaring metric variables
2022-09-27 21:25:24,796:INFO:Importing untrained model
2022-09-27 21:25:24,802:INFO:Linear Discriminant Analysis Imported succesfully
2022-09-27 21:25:24,816:INFO:Starting cross validation
2022-09-27 21:25:24,816:WARNING:create_model() for lda raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,817:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,818:INFO:Initializing create_model()
2022-09-27 21:25:24,818:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,818:INFO:Checking exceptions
2022-09-27 21:25:24,818:INFO:Importing libraries
2022-09-27 21:25:24,819:INFO:Copying training dataset
2022-09-27 21:25:24,820:INFO:Defining folds
2022-09-27 21:25:24,820:INFO:Declaring metric variables
2022-09-27 21:25:24,826:INFO:Importing untrained model
2022-09-27 21:25:24,833:INFO:Linear Discriminant Analysis Imported succesfully
2022-09-27 21:25:24,847:INFO:Starting cross validation
2022-09-27 21:25:24,847:ERROR:create_model() for lda raised an exception:
2022-09-27 21:25:24,848:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,848:INFO:Initializing Extra Trees Classifier
2022-09-27 21:25:24,848:INFO:Total runtime is 0.012514412403106688 minutes
2022-09-27 21:25:24,855:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,856:INFO:Initializing create_model()
2022-09-27 21:25:24,856:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,856:INFO:Checking exceptions
2022-09-27 21:25:24,856:INFO:Importing libraries
2022-09-27 21:25:24,856:INFO:Copying training dataset
2022-09-27 21:25:24,857:INFO:Defining folds
2022-09-27 21:25:24,857:INFO:Declaring metric variables
2022-09-27 21:25:24,863:INFO:Importing untrained model
2022-09-27 21:25:24,869:INFO:Extra Trees Classifier Imported succesfully
2022-09-27 21:25:24,886:INFO:Starting cross validation
2022-09-27 21:25:24,886:WARNING:create_model() for et raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,887:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,887:INFO:Initializing create_model()
2022-09-27 21:25:24,887:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,887:INFO:Checking exceptions
2022-09-27 21:25:24,888:INFO:Importing libraries
2022-09-27 21:25:24,888:INFO:Copying training dataset
2022-09-27 21:25:24,889:INFO:Defining folds
2022-09-27 21:25:24,889:INFO:Declaring metric variables
2022-09-27 21:25:24,895:INFO:Importing untrained model
2022-09-27 21:25:24,901:INFO:Extra Trees Classifier Imported succesfully
2022-09-27 21:25:24,914:INFO:Starting cross validation
2022-09-27 21:25:24,914:ERROR:create_model() for et raised an exception:
2022-09-27 21:25:24,915:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,915:INFO:Initializing Extreme Gradient Boosting
2022-09-27 21:25:24,915:INFO:Total runtime is 0.013628093401590982 minutes
2022-09-27 21:25:24,923:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,923:INFO:Initializing create_model()
2022-09-27 21:25:24,923:INFO:create_model(estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,923:INFO:Checking exceptions
2022-09-27 21:25:24,924:INFO:Importing libraries
2022-09-27 21:25:24,924:INFO:Copying training dataset
2022-09-27 21:25:24,924:INFO:Defining folds
2022-09-27 21:25:24,924:INFO:Declaring metric variables
2022-09-27 21:25:24,930:INFO:Importing untrained model
2022-09-27 21:25:24,937:INFO:Extreme Gradient Boosting Imported succesfully
2022-09-27 21:25:24,951:INFO:Starting cross validation
2022-09-27 21:25:24,951:WARNING:create_model() for xgboost raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:24,952:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,952:INFO:Initializing create_model()
2022-09-27 21:25:24,952:INFO:create_model(estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,952:INFO:Checking exceptions
2022-09-27 21:25:24,952:INFO:Importing libraries
2022-09-27 21:25:24,953:INFO:Copying training dataset
2022-09-27 21:25:24,953:INFO:Defining folds
2022-09-27 21:25:24,954:INFO:Declaring metric variables
2022-09-27 21:25:24,959:INFO:Importing untrained model
2022-09-27 21:25:24,969:INFO:Extreme Gradient Boosting Imported succesfully
2022-09-27 21:25:24,982:INFO:Starting cross validation
2022-09-27 21:25:24,982:ERROR:create_model() for xgboost raised an exception:
2022-09-27 21:25:24,983:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:24,983:INFO:Initializing Light Gradient Boosting Machine
2022-09-27 21:25:24,984:INFO:Total runtime is 0.014774998029073078 minutes
2022-09-27 21:25:24,991:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:24,991:INFO:Initializing create_model()
2022-09-27 21:25:24,991:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:24,991:INFO:Checking exceptions
2022-09-27 21:25:24,991:INFO:Importing libraries
2022-09-27 21:25:24,991:INFO:Copying training dataset
2022-09-27 21:25:24,992:INFO:Defining folds
2022-09-27 21:25:24,992:INFO:Declaring metric variables
2022-09-27 21:25:24,999:INFO:Importing untrained model
2022-09-27 21:25:25,005:INFO:Light Gradient Boosting Machine Imported succesfully
2022-09-27 21:25:25,020:INFO:Starting cross validation
2022-09-27 21:25:25,020:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:25,020:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:25,020:INFO:Initializing create_model()
2022-09-27 21:25:25,020:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:25,020:INFO:Checking exceptions
2022-09-27 21:25:25,020:INFO:Importing libraries
2022-09-27 21:25:25,021:INFO:Copying training dataset
2022-09-27 21:25:25,021:INFO:Defining folds
2022-09-27 21:25:25,021:INFO:Declaring metric variables
2022-09-27 21:25:25,027:INFO:Importing untrained model
2022-09-27 21:25:25,033:INFO:Light Gradient Boosting Machine Imported succesfully
2022-09-27 21:25:25,046:INFO:Starting cross validation
2022-09-27 21:25:25,046:ERROR:create_model() for lightgbm raised an exception:
2022-09-27 21:25:25,047:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:25,047:INFO:Initializing CatBoost Classifier
2022-09-27 21:25:25,047:INFO:Total runtime is 0.015822192033131916 minutes
2022-09-27 21:25:25,054:INFO:SubProcess create_model() called ==================================
2022-09-27 21:25:25,055:INFO:Initializing create_model()
2022-09-27 21:25:25,055:INFO:create_model(estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:25,055:INFO:Checking exceptions
2022-09-27 21:25:25,055:INFO:Importing libraries
2022-09-27 21:25:25,055:INFO:Copying training dataset
2022-09-27 21:25:25,056:INFO:Defining folds
2022-09-27 21:25:25,056:INFO:Declaring metric variables
2022-09-27 21:25:25,061:INFO:Importing untrained model
2022-09-27 21:25:25,067:INFO:CatBoost Classifier Imported succesfully
2022-09-27 21:25:25,092:INFO:Starting cross validation
2022-09-27 21:25:25,092:WARNING:create_model() for catboost raised an exception or returned all 0.0, trying without fit_kwargs:
2022-09-27 21:25:25,092:WARNING:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:25,093:INFO:Initializing create_model()
2022-09-27 21:25:25,093:INFO:create_model(estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=2, shuffle=True), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x00000222F5ADA340>, kwargs={})
2022-09-27 21:25:25,093:INFO:Checking exceptions
2022-09-27 21:25:25,093:INFO:Importing libraries
2022-09-27 21:25:25,093:INFO:Copying training dataset
2022-09-27 21:25:25,093:INFO:Defining folds
2022-09-27 21:25:25,094:INFO:Declaring metric variables
2022-09-27 21:25:25,099:INFO:Importing untrained model
2022-09-27 21:25:25,105:INFO:CatBoost Classifier Imported succesfully
2022-09-27 21:25:25,118:INFO:Starting cross validation
2022-09-27 21:25:25,118:ERROR:create_model() for catboost raised an exception:
2022-09-27 21:25:25,119:ERROR:Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 217, in add_estimator_to_pipeline
    assert hasattr(pipeline._final_estimator, "predict")
AttributeError: 'list' object has no attribute '_final_estimator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\tabular.py", line 3080, in create_model_supervised
    with estimator_pipeline(_internal_pipeline, model) as pipeline_with_model:
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 199, in __enter__
    add_estimator_to_pipeline(self.pipeline, self.estimator)
  File "C:\Users\18040\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pipeline.py", line 220, in add_estimator_to_pipeline
    pipeline.steps.append((name, estimator))
AttributeError: 'list' object has no attribute 'steps'

2022-09-27 21:25:25,129:INFO:create_model_container: 0
2022-09-27 21:25:25,130:INFO:master_model_container: 0
2022-09-27 21:25:25,130:INFO:display_container: 1
2022-09-27 21:25:25,130:INFO:[]
2022-09-27 21:25:25,130:INFO:compare_models() succesfully completed......................................
2022-09-27 21:27:23,877:INFO:PyCaret Supervised Module
2022-09-27 21:27:23,877:INFO:ML Usecase: classification
2022-09-27 21:27:23,877:INFO:version 2.2.2
2022-09-27 21:27:23,877:INFO:Initializing setup()
2022-09-27 21:27:23,877:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=True, multicollinearity_threshold=0.95, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:27:23,877:INFO:Checking environment
2022-09-27 21:27:23,877:INFO:python_version: 3.9.12
2022-09-27 21:27:23,877:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:27:23,878:INFO:machine: AMD64
2022-09-27 21:27:23,878:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:27:23,878:INFO:Memory: svmem(total=16959000576, available=7121551360, percent=58.0, used=9837449216, free=7121551360)
2022-09-27 21:27:23,878:INFO:Physical Core: 4
2022-09-27 21:27:23,878:INFO:Logical Core: 8
2022-09-27 21:27:23,878:INFO:Checking libraries
2022-09-27 21:27:23,878:INFO:pd==1.4.2
2022-09-27 21:27:23,878:INFO:numpy==1.21.5
2022-09-27 21:27:23,878:INFO:sklearn==1.1.2
2022-09-27 21:27:23,878:INFO:xgboost==1.6.1
2022-09-27 21:27:23,878:INFO:lightgbm==3.3.2
2022-09-27 21:27:23,878:INFO:catboost==1.0.6
2022-09-27 21:27:23,878:INFO:mlflow==1.28.0
2022-09-27 21:27:23,879:INFO:Checking Exceptions
2022-09-27 21:27:23,879:INFO:Declaring global variables
2022-09-27 21:27:23,879:INFO:USI: fbe1
2022-09-27 21:27:23,879:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:27:23,879:INFO:Preparing display monitor
2022-09-27 21:27:23,879:INFO:Preparing display monitor
2022-09-27 21:27:23,888:INFO:Importing libraries
2022-09-27 21:27:23,888:INFO:Copying data for preprocessing
2022-09-27 21:27:23,894:INFO:Declaring preprocessing parameters
2022-09-27 21:27:23,895:INFO:Creating preprocessing pipeline
2022-09-27 21:27:23,896:INFO:Preprocessing pipeline created successfully
2022-09-27 21:27:23,896:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:27:23,897:INFO:Creating global containers
2022-09-27 21:27:23,898:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=2,
                       sampling_strategy='auto'))],
         verbose=False)
2022-09-27 21:27:27,107:INFO:Creating grid variables
2022-09-27 21:27:27,116:INFO:create_model_container: 0
2022-09-27 21:27:27,116:INFO:master_model_container: 0
2022-09-27 21:27:27,116:INFO:display_container: 0
2022-09-27 21:28:00,749:INFO:PyCaret Supervised Module
2022-09-27 21:28:00,749:INFO:ML Usecase: classification
2022-09-27 21:28:00,749:INFO:version 2.2.2
2022-09-27 21:28:00,749:INFO:Initializing setup()
2022-09-27 21:28:00,749:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:28:00,749:INFO:Checking environment
2022-09-27 21:28:00,749:INFO:python_version: 3.9.12
2022-09-27 21:28:00,749:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:28:00,750:INFO:machine: AMD64
2022-09-27 21:28:00,750:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:28:00,750:INFO:Memory: svmem(total=16959000576, available=7095468032, percent=58.2, used=9863532544, free=7095468032)
2022-09-27 21:28:00,750:INFO:Physical Core: 4
2022-09-27 21:28:00,750:INFO:Logical Core: 8
2022-09-27 21:28:00,750:INFO:Checking libraries
2022-09-27 21:28:00,750:INFO:pd==1.4.2
2022-09-27 21:28:00,750:INFO:numpy==1.21.5
2022-09-27 21:28:00,750:INFO:sklearn==1.1.2
2022-09-27 21:28:00,750:INFO:xgboost==1.6.1
2022-09-27 21:28:00,750:INFO:lightgbm==3.3.2
2022-09-27 21:28:00,750:INFO:catboost==1.0.6
2022-09-27 21:28:00,750:INFO:mlflow==1.28.0
2022-09-27 21:28:00,751:INFO:Checking Exceptions
2022-09-27 21:28:00,751:INFO:Declaring global variables
2022-09-27 21:28:00,751:INFO:USI: c180
2022-09-27 21:28:00,751:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:28:00,751:INFO:Preparing display monitor
2022-09-27 21:28:00,751:INFO:Preparing display monitor
2022-09-27 21:28:00,760:INFO:Importing libraries
2022-09-27 21:28:00,760:INFO:Copying data for preprocessing
2022-09-27 21:28:00,767:INFO:Declaring preprocessing parameters
2022-09-27 21:28:00,768:INFO:Creating preprocessing pipeline
2022-09-27 21:28:00,770:INFO:Preprocessing pipeline created successfully
2022-09-27 21:28:00,770:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:28:00,771:INFO:Creating global containers
2022-09-27 21:28:16,181:INFO:PyCaret Supervised Module
2022-09-27 21:28:16,181:INFO:ML Usecase: classification
2022-09-27 21:28:16,181:INFO:version 2.2.2
2022-09-27 21:28:16,182:INFO:Initializing setup()
2022-09-27 21:28:16,182:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:28:16,182:INFO:Checking environment
2022-09-27 21:28:16,182:INFO:python_version: 3.9.12
2022-09-27 21:28:16,182:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:28:16,182:INFO:machine: AMD64
2022-09-27 21:28:16,182:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:28:16,182:INFO:Memory: svmem(total=16959000576, available=7099973632, percent=58.1, used=9859026944, free=7099973632)
2022-09-27 21:28:16,182:INFO:Physical Core: 4
2022-09-27 21:28:16,182:INFO:Logical Core: 8
2022-09-27 21:28:16,182:INFO:Checking libraries
2022-09-27 21:28:16,182:INFO:pd==1.4.2
2022-09-27 21:28:16,182:INFO:numpy==1.21.5
2022-09-27 21:28:16,182:INFO:sklearn==1.1.2
2022-09-27 21:28:16,182:INFO:xgboost==1.6.1
2022-09-27 21:28:16,183:INFO:lightgbm==3.3.2
2022-09-27 21:28:16,183:INFO:catboost==1.0.6
2022-09-27 21:28:16,183:INFO:mlflow==1.28.0
2022-09-27 21:28:16,183:INFO:Checking Exceptions
2022-09-27 21:28:16,183:INFO:Declaring global variables
2022-09-27 21:28:16,183:INFO:USI: 3c3d
2022-09-27 21:28:16,183:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:28:16,183:INFO:Preparing display monitor
2022-09-27 21:28:16,183:INFO:Preparing display monitor
2022-09-27 21:28:16,193:INFO:Importing libraries
2022-09-27 21:28:16,193:INFO:Copying data for preprocessing
2022-09-27 21:28:16,198:INFO:Declaring preprocessing parameters
2022-09-27 21:28:16,199:INFO:Creating preprocessing pipeline
2022-09-27 21:28:16,201:INFO:Preprocessing pipeline created successfully
2022-09-27 21:28:16,201:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:28:16,201:INFO:Creating global containers
2022-09-27 21:28:16,201:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:28:19,820:INFO:Creating grid variables
2022-09-27 21:28:19,828:INFO:create_model_container: 0
2022-09-27 21:28:19,828:INFO:master_model_container: 0
2022-09-27 21:28:19,829:INFO:display_container: 0
2022-09-27 21:38:49,808:INFO:PyCaret Supervised Module
2022-09-27 21:38:49,808:INFO:ML Usecase: classification
2022-09-27 21:38:49,809:INFO:version 2.2.2
2022-09-27 21:38:49,809:INFO:Initializing setup()
2022-09-27 21:38:49,809:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:38:49,809:INFO:Checking environment
2022-09-27 21:38:49,809:INFO:python_version: 3.9.12
2022-09-27 21:38:49,809:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:38:49,809:INFO:machine: AMD64
2022-09-27 21:38:49,809:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:38:49,809:INFO:Memory: svmem(total=16959000576, available=6437662720, percent=62.0, used=10521337856, free=6437662720)
2022-09-27 21:38:49,809:INFO:Physical Core: 4
2022-09-27 21:38:49,809:INFO:Logical Core: 8
2022-09-27 21:38:49,809:INFO:Checking libraries
2022-09-27 21:38:49,809:INFO:pd==1.4.2
2022-09-27 21:38:49,809:INFO:numpy==1.21.5
2022-09-27 21:38:49,809:INFO:sklearn==1.1.2
2022-09-27 21:38:49,809:INFO:xgboost==1.6.1
2022-09-27 21:38:49,809:INFO:lightgbm==3.3.2
2022-09-27 21:38:49,810:INFO:catboost==1.0.6
2022-09-27 21:38:49,810:INFO:mlflow==1.28.0
2022-09-27 21:38:49,810:INFO:Checking Exceptions
2022-09-27 21:38:49,810:INFO:Declaring global variables
2022-09-27 21:38:49,810:INFO:USI: cb62
2022-09-27 21:38:49,810:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:38:49,810:INFO:Preparing display monitor
2022-09-27 21:38:49,810:INFO:Preparing display monitor
2022-09-27 21:38:49,821:INFO:Importing libraries
2022-09-27 21:38:49,821:INFO:Copying data for preprocessing
2022-09-27 21:38:49,828:INFO:Declaring preprocessing parameters
2022-09-27 21:38:49,829:INFO:Creating preprocessing pipeline
2022-09-27 21:38:49,833:INFO:Preprocessing pipeline created successfully
2022-09-27 21:38:49,833:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:38:49,833:INFO:Creating global containers
2022-09-27 21:38:49,833:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-09-27 21:38:53,737:INFO:Creating grid variables
2022-09-27 21:38:53,747:INFO:create_model_container: 0
2022-09-27 21:38:53,747:INFO:master_model_container: 0
2022-09-27 21:38:53,747:INFO:display_container: 0
2022-09-27 21:39:21,335:INFO:PyCaret Supervised Module
2022-09-27 21:39:21,335:INFO:ML Usecase: classification
2022-09-27 21:39:21,335:INFO:version 2.2.2
2022-09-27 21:39:21,335:INFO:Initializing setup()
2022-09-27 21:39:21,335:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-09-27 21:39:21,335:INFO:Checking environment
2022-09-27 21:39:21,335:INFO:python_version: 3.9.12
2022-09-27 21:39:21,335:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-09-27 21:39:21,336:INFO:machine: AMD64
2022-09-27 21:39:21,336:INFO:platform: Windows-10-10.0.19044-SP0
2022-09-27 21:39:21,336:INFO:Memory: svmem(total=16959000576, available=6355050496, percent=62.5, used=10603950080, free=6355050496)
2022-09-27 21:39:21,336:INFO:Physical Core: 4
2022-09-27 21:39:21,336:INFO:Logical Core: 8
2022-09-27 21:39:21,336:INFO:Checking libraries
2022-09-27 21:39:21,336:INFO:pd==1.4.2
2022-09-27 21:39:21,336:INFO:numpy==1.21.5
2022-09-27 21:39:21,336:INFO:sklearn==1.1.2
2022-09-27 21:39:21,336:INFO:xgboost==1.6.1
2022-09-27 21:39:21,336:INFO:lightgbm==3.3.2
2022-09-27 21:39:21,336:INFO:catboost==1.0.6
2022-09-27 21:39:21,336:INFO:mlflow==1.28.0
2022-09-27 21:39:21,336:INFO:Checking Exceptions
2022-09-27 21:39:21,336:INFO:Declaring global variables
2022-09-27 21:39:21,336:INFO:USI: d3cd
2022-09-27 21:39:21,336:INFO:pycaret_globals: {'seed', '_gpu_n_jobs_param', '_all_metrics', 'n_jobs_param', 'html_param', 'prep_pipe', 'data_before_preprocess', 'master_model_container', 'fold_groups_param', 'fix_imbalance_method_param', 'iterative_imputation_iters_param', 'logging_param', 'USI', '_internal_pipeline', 'transform_target_method_param', 'X', '_available_plots', 'exp_name_log', 'log_plots_param', 'experiment__', 'display_container', 'y', 'pycaret_globals', '_all_models', '_ml_usecase', 'fold_generator', 'imputation_regressor', 'y_test', 'fix_imbalance_param', '_all_models_internal', 'gpu_param', 'fold_param', 'imputation_classifier', 'transform_target_param', 'X_test', 'stratify_param', 'target_param', 'fold_shuffle_param', 'X_train', 'create_model_container', 'y_train'}
2022-09-27 21:39:21,336:INFO:Preparing display monitor
2022-09-27 21:39:21,337:INFO:Preparing display monitor
2022-09-27 21:39:21,348:INFO:Importing libraries
2022-09-27 21:39:21,348:INFO:Copying data for preprocessing
2022-09-27 21:39:21,354:INFO:Declaring preprocessing parameters
2022-09-27 21:39:21,355:INFO:Creating preprocessing pipeline
2022-09-27 21:39:21,357:INFO:Preprocessing pipeline created successfully
2022-09-27 21:39:21,357:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-09-27 21:39:21,358:INFO:Creating global containers
2022-10-10 21:37:15,898:INFO:PyCaret Supervised Module
2022-10-10 21:37:15,898:INFO:ML Usecase: classification
2022-10-10 21:37:15,899:INFO:version 2.2.2
2022-10-10 21:37:15,899:INFO:Initializing setup()
2022-10-10 21:37:15,899:INFO:setup(target=sentiment, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=2, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-10-10 21:37:15,899:INFO:Checking environment
2022-10-10 21:37:15,899:INFO:python_version: 3.9.12
2022-10-10 21:37:15,899:INFO:python_build: ('main', 'Apr  4 2022 05:22:27')
2022-10-10 21:37:15,899:INFO:machine: AMD64
2022-10-10 21:37:15,899:INFO:platform: Windows-10-10.0.19044-SP0
2022-10-10 21:37:15,899:INFO:Memory: svmem(total=16959000576, available=8439136256, percent=50.2, used=8519864320, free=8439136256)
2022-10-10 21:37:15,899:INFO:Physical Core: 4
2022-10-10 21:37:15,899:INFO:Logical Core: 8
2022-10-10 21:37:15,899:INFO:Checking libraries
2022-10-10 21:37:15,899:INFO:pd==1.4.2
2022-10-10 21:37:15,899:INFO:numpy==1.21.5
2022-10-10 21:37:15,899:INFO:sklearn==1.1.2
2022-10-10 21:37:15,923:INFO:xgboost==1.6.1
2022-10-10 21:37:15,923:INFO:lightgbm==3.3.2
2022-10-10 21:37:15,939:INFO:catboost==1.0.6
2022-10-10 21:37:16,585:INFO:mlflow==1.28.0
2022-10-10 21:37:16,585:INFO:Checking Exceptions
2022-10-10 21:37:16,585:INFO:Declaring global variables
2022-10-10 21:37:16,585:INFO:USI: 1d74
2022-10-10 21:37:16,585:INFO:pycaret_globals: {'master_model_container', 'y', '_all_models_internal', 'iterative_imputation_iters_param', 'fix_imbalance_method_param', 'y_train', 'display_container', 'logging_param', '_all_models', 'stratify_param', '_gpu_n_jobs_param', 'target_param', 'log_plots_param', '_internal_pipeline', 'n_jobs_param', 'transform_target_param', 'fix_imbalance_param', '_available_plots', 'fold_param', 'create_model_container', 'X', 'transform_target_method_param', 'pycaret_globals', '_all_metrics', 'imputation_classifier', 'seed', 'gpu_param', 'USI', 'prep_pipe', 'experiment__', 'imputation_regressor', 'X_train', 'X_test', '_ml_usecase', 'exp_name_log', 'fold_shuffle_param', 'data_before_preprocess', 'html_param', 'fold_generator', 'y_test', 'fold_groups_param'}
2022-10-10 21:37:16,585:INFO:Preparing display monitor
2022-10-10 21:37:16,585:INFO:Preparing display monitor
2022-10-10 21:37:16,594:INFO:Importing libraries
2022-10-10 21:37:16,594:INFO:Copying data for preprocessing
2022-10-10 21:37:16,599:INFO:Declaring preprocessing parameters
2022-10-10 21:37:16,600:INFO:Creating preprocessing pipeline
2022-10-10 21:37:16,603:INFO:Preprocessing pipeline created successfully
2022-10-10 21:37:16,603:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-10-10 21:37:16,603:INFO:Creating global containers
2022-10-10 21:37:16,604:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-10-10 21:37:22,393:INFO:Creating grid variables
2022-10-10 21:37:22,401:INFO:create_model_container: 0
2022-10-10 21:37:22,402:INFO:master_model_container: 0
2022-10-10 21:37:22,402:INFO:display_container: 0
